### ISSUE TITLE
请问参考答案，是如何获取的？

### ISSUE THREAD

**Issue by MrSeven77** [CLUEbenchmark/SuperCLUE-Role#1]
> 结合参考答案使用超级模型进行打分，模型回答的得分是对应各个维度得分的平均值。

请问这里参考答案，是针对所有测评维度都提供了的吗？是人工编写的答案还是超级模型生成的？超级模型评价的时候，会出现参考答案和带测评模型答案冲突，但是都正确的情况吗？

**Comment by brightmart** [comment]
都有的都提供了。经过人工修订的答案。参考答案不是唯一答案，只是定义良好的答案。

**Comment by MrSeven77** [comment]
thx
